### ISSUE TITLE
ace-Plugin.js breaks MainTiddlyServer saving

### ISSUE THREAD

**Issue by YakovL** [qbroker/ace-Plugin.js#2]
Hey Okido, I've noticed that the plugin breaks MainTiddlyServer saving causing a (non-critical) error:

> Error while saving. Server: <br /> <b>Warning</b>: DOMDocument::loadHTML(): Invalid char in CDATA 0x1 in Entity, line: 217 in <b>D:\data\based_here\innernet\localhost\innernet\index.php</b> on line <b>1191</b><br /> <br /> <b>Warning</b>: DOMDocument::loadHTML(): Invalid char in CDATA 0x1 in Entity, line: 217 in <b>D:\data\based_here\innernet\localhost\innernet\index.php</b> on line <b>1191</b><br /> <br /> <b>Warning</b>: DOMDocument::loadHTML(): Invalid char in CDATA 0x1 in Entity, line: 217 in <b>D:\data\based_here\innernet\localhost\innernet\index.php</b> on line <b>1191</b><br /> <br /> <b>Warning</b>: DOMDocument::loadHTML(): Invalid char in CDATA 0x1 in Entity, line: 217 in <b>D:\data\based_here\innernet\localhost\innernet\index.php</b> on line <b>1191</b><br /> saved

(this results in an incorrect indication of `dirty` since MTS only thinks the saving was successful if the backend returns just "saved"; this may be updated in the future, but for now..)

The cause is the  (`'\x01\x01'`) bit present twice in the [line 216](https://github.com/qbroker/ace-Plugin.js/blob/c90481f25fa23a82d18dd2805c1de9ef7d392a78/plugins/ace-Plugin.js#L216) (removing those symbols restores saving).

Could you clarify what are they/why they are used/can they be substituted with something else?

**Comment by qbroker** [comment]
Thanks for reporting Yakov,

I compared some files, the problem is growing over time. 
The original ace.js file contains a placeholder "\x01\x01", after minify "\x01\x01"  is translated into "••", and after a pull and merge request it becomes  "��".
I will have a look if it is possible to escape the placeholder or not minify it.

Have a nice day, Okido

**Comment by qbroker** [comment]
Hello Yakov,

I tested on Linux Mint 18.1 with XAMP for Linux 8.2.4-0 and MainTiddlyServer 1.7.1.
It is possible to replicate.
The TWC ace-Plugin.js.html from GitHub saves without any problem.
When the ace plugin from the GitHub plugin folder is added with copy/paste, saving fails, it only saves a TWC with one tiddler object.
This saving with only one tiddler happens more often, but I do not know why.
Countermeasure for the moment is to set **config.options.chkUsePreForStorage = true;** in a tiddler tagged with systemConfig.

Have a nice day, Okido
